# Generated by Django 2.1.5 on 2019-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_display',
            field=models.BooleanField(default=True, help_text="Définit si l'article doit être consultable", verbose_name='Article visible ?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_index',
            field=models.BooleanField(default=True, help_text="Définit si l'article doit être indexé et affiché sur la liste des articles", verbose_name='Article indéxé ?'),
        ),
    ]
